"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import type { Artifact } from "@prisma/client";
import { ArtifactState } from "@prisma/client";
import { DownloadIcon } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { TextDiff } from "./text-diff";
import { toastError, toastSuccess } from "@/lib/ui/toast";
import {
  approveArtifactAction,
  editArtifactAction,
  rejectArtifactAction,
  requireReviewAction,
} from "@/app/(authed)/applications/[id]/_actions";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  artifact: Artifact;
  applicationId: string;
  versions: Artifact[];
  signedReadUrl?: string | null;
};

export function ApprovalGate({
  open,
  onOpenChange,
  artifact,
  applicationId,
  versions,
  signedReadUrl,
}: Props) {
  const router = useRouter();
  const [pending, setPending] = React.useState(false);
  const [editing, setEditing] = React.useState(false);
  const [editedText, setEditedText] = React.useState(artifact.contentText ?? "");
  const [compareWithId, setCompareWithId] = React.useState<string | null>(null);

  const otherVersions = versions.filter((v) => v.id !== artifact.id);
  const compareWith = compareWithId
    ? versions.find((v) => v.id === compareWithId) ?? null
    : null;

  const canMutate =
    artifact.state === ArtifactState.DRAFT ||
    artifact.state === ArtifactState.PENDING_REVIEW;

  async function moveToReview() {
    if (artifact.state !== ArtifactState.DRAFT) return;
    setPending(true);
    try {
      const res = await requireReviewAction(artifact.id);
      if (!res.ok) toastError(res.error);
      else router.refresh();
    } finally {
      setPending(false);
    }
  }

  async function approve() {
    setPending(true);
    try {
      const res = await approveArtifactAction(artifact.id, applicationId);
      if (!res.ok) {
        toastError(res.error);
        return;
      }
      toastSuccess("Approved");
      onOpenChange(false);
      router.refresh();
    } finally {
      setPending(false);
    }
  }

  async function reject() {
    setPending(true);
    try {
      const res = await rejectArtifactAction(artifact.id, applicationId);
      if (!res.ok) {
        toastError(res.error);
        return;
      }
      toastSuccess("Rejected");
      onOpenChange(false);
      router.refresh();
    } finally {
      setPending(false);
    }
  }

  async function saveEdit() {
    setPending(true);
    try {
      const res = await editArtifactAction(artifact.id, applicationId, editedText);
      if (!res.ok) {
        toastError(res.error);
        return;
      }
      toastSuccess("Saved new version");
      setEditing(false);
      onOpenChange(false);
      router.refresh();
    } finally {
      setPending(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-5xl">
        <DialogHeader>
          <DialogTitle>Approval gate</DialogTitle>
          <DialogDescription>
            Review and approve before this artifact can be used externally.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4 md:grid-cols-[18rem_1fr]">
          <aside className="flex flex-col gap-3 text-sm">
            <MetaRow label="Type" value={<Badge variant="outline">{artifact.type}</Badge>} />
            <MetaRow label="State" value={<Badge>{artifact.state}</Badge>} />
            <MetaRow label="Version" value={`v${artifact.versionNumber}`} />
            <MetaRow label="Generated by" value={artifact.generatedByWorker} />
            <MetaRow
              label="Generated at"
              value={new Date(artifact.generatedAt).toLocaleString()}
            />
            {signedReadUrl ? (
              <a
                href={signedReadUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
              >
                <DownloadIcon className="size-3" /> Download original
              </a>
            ) : null}
            {otherVersions.length > 0 ? (
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted-foreground">
                  Compare with version
                </label>
                <select
                  className="h-7 rounded-md border border-input bg-transparent px-2 text-xs dark:bg-input/30"
                  value={compareWithId ?? ""}
                  onChange={(e) => setCompareWithId(e.target.value || null)}
                >
                  <option value="">— none —</option>
                  {otherVersions.map((v) => (
                    <option key={v.id} value={v.id}>
                      v{v.versionNumber} ({v.state})
                    </option>
                  ))}
                </select>
              </div>
            ) : null}
          </aside>

          <section className="flex flex-col gap-3">
            {editing ? (
              <Textarea
                rows={20}
                value={editedText}
                onChange={(e) => setEditedText(e.target.value)}
              />
            ) : compareWith && artifact.contentText && compareWith.contentText ? (
              <TextDiff a={compareWith.contentText} b={artifact.contentText} />
            ) : (
              <pre className="max-h-[28rem] overflow-auto rounded-lg border border-input bg-muted/30 p-3 text-xs whitespace-pre-wrap">
                {artifact.contentText ?? "(no inline text — use Download original)"}
              </pre>
            )}
          </section>
        </div>

        <DialogFooter>
          <div className="mr-auto flex gap-2">
            {artifact.state === ArtifactState.DRAFT ? (
              <Button variant="outline" size="sm" disabled={pending} onClick={moveToReview}>
                Move to pending review
              </Button>
            ) : null}
          </div>
          {editing ? (
            <>
              <Button variant="outline" disabled={pending} onClick={() => setEditing(false)}>
                Cancel edit
              </Button>
              <Button disabled={pending} onClick={saveEdit}>
                Save as new version
              </Button>
            </>
          ) : (
            <>
              <Tooltip>
                <TooltipTrigger
                  render={
                    <Button variant="outline" disabled>
                      Regenerate
                    </Button>
                  }
                />
                <TooltipContent>
                  Available once a worker generates this artifact type.
                </TooltipContent>
              </Tooltip>
              <Button
                variant="outline"
                disabled={pending || !canMutate || artifact.contentText == null}
                onClick={() => {
                  setEditedText(artifact.contentText ?? "");
                  setEditing(true);
                }}
              >
                Edit
              </Button>
              <Button
                variant="destructive"
                disabled={pending || !canMutate}
                onClick={reject}
              >
                Reject
              </Button>
              <Button disabled={pending || !canMutate} onClick={approve}>
                Approve
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function MetaRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-xs text-muted-foreground">{label}</span>
      <span className="text-sm">{value}</span>
    </div>
  );
}
