-- AlterEnum: add EVALUATION_REGENERATION_REQUESTED and EVALUATION_GENERATION_FAILED
-- next to EVALUATION_GENERATED so they sort together in psql / Prisma Studio.
ALTER TYPE "EventType" ADD VALUE 'EVALUATION_REGENERATION_REQUESTED' AFTER 'EVALUATION_GENERATED';
ALTER TYPE "EventType" ADD VALUE 'EVALUATION_GENERATION_FAILED' AFTER 'EVALUATION_REGENERATION_REQUESTED';
