-- AlterEnum: add resume/cover-letter generation+regeneration event types
-- next to RESUME_GENERATED / COVER_LETTER_GENERATED so they sort together.
ALTER TYPE "EventType" ADD VALUE 'RESUME_GENERATION_FAILED' AFTER 'RESUME_GENERATED';
ALTER TYPE "EventType" ADD VALUE 'TAILORED_RESUME_REGENERATION_REQUESTED' AFTER 'RESUME_GENERATION_FAILED';
ALTER TYPE "EventType" ADD VALUE 'COVER_LETTER_GENERATION_FAILED' AFTER 'COVER_LETTER_GENERATED';
ALTER TYPE "EventType" ADD VALUE 'COVER_LETTER_REGENERATION_REQUESTED' AFTER 'COVER_LETTER_GENERATION_FAILED';
