"use client";

import * as React from "react";
import type { Artifact } from "@prisma/client";
import { ArtifactState } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ApprovalGate } from "@/components/artifacts/approval-gate";
import { ManualUploadButton } from "@/components/artifacts/manual-upload-button";

type Props = {
  applicationId: string;
  artifacts: Artifact[];
};

export function ArtifactsTab({ applicationId, artifacts }: Props) {
  const [openId, setOpenId] = React.useState<string | null>(null);
  const open = openId ? artifacts.find((a) => a.id === openId) ?? null : null;
  const versionsForOpen = open
    ? artifacts.filter((a) => a.type === open.type).sort((a, b) => a.versionNumber - b.versionNumber)
    : [];

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          All artifacts for this application. Click a row to open in the approval gate.
        </p>
        <ManualUploadButton applicationId={applicationId} />
      </div>
      {artifacts.length === 0 ? (
        <p className="text-sm text-muted-foreground">No artifacts yet.</p>
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Type</TableHead>
              <TableHead>State</TableHead>
              <TableHead>Version</TableHead>
              <TableHead>Generated by</TableHead>
              <TableHead>Generated at</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {artifacts.map((a) => (
              <TableRow key={a.id}>
                <TableCell>
                  <Badge variant="outline">{a.type}</Badge>
                </TableCell>
                <TableCell>
                  <Badge variant={a.state === ArtifactState.APPROVED ? "default" : "secondary"}>
                    {a.state}
                  </Badge>
                </TableCell>
                <TableCell>v{a.versionNumber}</TableCell>
                <TableCell className="text-xs text-muted-foreground">
                  {a.generatedByWorker}
                </TableCell>
                <TableCell className="text-xs text-muted-foreground">
                  {new Date(a.generatedAt).toLocaleString("en-US")}
                </TableCell>
                <TableCell className="text-right">
                  <Button size="sm" variant="outline" onClick={() => setOpenId(a.id)}>
                    Open
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
      {open ? (
        <ApprovalGate
          open={true}
          onOpenChange={(o) => {
            if (!o) setOpenId(null);
          }}
          artifact={open}
          applicationId={applicationId}
          versions={versionsForOpen}
        />
      ) : null}
    </div>
  );
}
